default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:  <%= ENV['DATABASE_PASSWORD'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: site_builder_development

test:
  <<: *default
  database: site_builder_test
